### ISSUE TITLE
I did not get the complete transcript

### ISSUE THREAD

**Issue by learner0333** [thomasmol/cog-whisper-diarization#11]
I am using the replicate for the transcript and Diarization.
I got very good results. But I am not getting the full transcript and diarization data for the following video:

https://www.youtube.com/watch?v=FLEaCRvGmKM

I have downloaded the video and passed it to replicate. I get the transcript and diarizationf of first 18 minutes or so. will you please update me about it?

**Comment by thomasmol** [comment]
Hi! this might be due to the model thinking the audio has ended. This happens sometimes during long pauses where there is no speech (singing is also difficult to recognize). I don't have a good solution for you right now, the only thing I can suggest is try cutting the video into segments where there is only speech. Let me know if this helps!
